services: # Cada servicio es un contenedor independiente
  db:
    image: postgres:15 # Software que contiene el contenedor
    environment: # La configuración, se define el nombre de la base de datos y la contraseña
      - POSTGRES_DB=odoo_dev
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=odoo
    volumes: 
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped  # mejor que always para desarrollo



  odoo:
    image: odoo:17.0
    depends_on:
      - db
    volumes: 
      - ./custom_addons:/mnt/custom_addons
      - ./quilsoft_addons:/mnt/quilsoft_addons
      - ./odoo.conf:/etc/odoo/odoo.conf # Se sincroniza una carpeta de la Pc con el contenedor
      - odoo-web-data:/var/lib/odoo # named volumes
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${DB_PASSWORD}
    command: odoo --dev=all --config=/etc/odoo/odoo.conf # Se ejecuta apenas se enciende el contenedor
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data: